/*
 * SaisieTemps.java
 *
 * Created on __DATE__, __TIME__
 */

package fr.gsmp.plongee.nage.gui;

import java.sql.Time;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DateEditor;
import javax.swing.SpinnerDateModel;

import org.springframework.context.support.ClassPathXmlApplicationContext;

import fr.gsmp.plongee.nage.dao.data.Participants;
import fr.gsmp.plongee.nage.services.manager.ParticipantsManager;

/**
 * 
 * @author __USER__
 */
public class SaisieTemps extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1626345441523270896L;
	private ParticipantsManager pm;
	private JSpinner timeSpinner;

	/** Creates new form SaisieTemps */
	public SaisieTemps(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		ClassPathXmlApplicationContext ctx = new ClassPathXmlApplicationContext(
				"classpath:applicationContextServices.xml");
		pm = (ParticipantsManager) ctx.getBean("participantsManagerImpl");

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		timeSpinner = new JSpinner(new SpinnerDateModel());

		tubaNumberLabel = new javax.swing.JLabel();
		tubaNumberField = new javax.swing.JTextField();
		timeLabel = new javax.swing.JLabel();
		timeTextField = new JSpinner.DateEditor(timeSpinner, "HH:mm:ss");
		timeSpinner.setEditor(timeTextField);
		Date date = new Date(0);
		date.setHours(0);
		timeSpinner.setValue(date);
		nextButton = new javax.swing.JButton();

		// setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridLayout(3, 2));

		tubaNumberLabel.setText("Num\u00e9ro de tuba");
		getContentPane().add(tubaNumberLabel);

		getContentPane().add(tubaNumberField);

		timeLabel.setText("Temps");
		getContentPane().add(timeLabel);
		getContentPane().add(timeSpinner);

		nextButton.setText("Suivant");
		nextButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nextButtonActionPerformed(evt);
			}
		});
		getContentPane().add(nextButton);

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {

		Participants participant = pm.getParticipantByTuba(Integer
				.valueOf(tubaNumberField.getText()));
		Time time = new Time(((Date)timeSpinner.getValue()).getTime());
		if (participant != null) {
			if (participant.getParticipanttemps()!=null && participant.getParticipanttemps().getTime() > 0) {
				if (JOptionPane
						.showConfirmDialog(
								this,
								"Le temps pour le tuba n°"
										+ tubaNumberField.getText()
										+ " a déjà été renseigné.\n Modifier la valeur ?",
								"Avertissement", JOptionPane.YES_NO_OPTION) == 0) {
					participant.setParticipanttemps(time);
					pm.save(participant);
					reset();
				}
			} else {

				participant.setParticipanttemps(time);
				pm.save(participant);
				reset();
			}
		} else {
			JOptionPane.showMessageDialog(this, "Numéro de tuba inconnu",
					"Erreur", JOptionPane.ERROR_MESSAGE);
		}

	}

	private void reset() {
		tubaNumberField.setText("");
		// timeTextField.setText("");
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton nextButton;
	private javax.swing.JLabel timeLabel;
	private DateEditor timeTextField;
	private javax.swing.JTextField tubaNumberField;
	private javax.swing.JLabel tubaNumberLabel;
	// End of variables declaration//GEN-END:variables

}